---
title: "QRM_Assignment_01"
author: "Max Cordon & Linus Kaiser"
date: 15-10-2021
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r Test, echo=F, message=FALSE}
library("readxl")
library("ggplot2")
library("sandwich")
library("dplyr")
```

```{r, echo = F}
car_data <- read_excel("QRMassignment20211008.xlsx")
```

# a)
```{r, echo = FALSE, message = FALSE, warning = "hide", results='hide'}
mm_car_data <- data.frame(moment = c("mean","median"),mean_n_median = c(mean(car_data$Price),median(car_data$Price)))

ggplot(car_data, aes(x=Price)) + 
  geom_histogram(col = "lightblue", fill = "lightblue") +
  geom_vline(data=mm_car_data,aes(xintercept=mean_n_median,linetype=factor(moment)),
             show.legend=TRUE, col = "darkgrey") +
  labs(linetype='Legend') + 
  theme(legend.position = c(0.85,0.85)) +
  scale_x_continuous(breaks = round(seq(0, 80000, by = 10000),1))
```

The dataset at hand has `r nrow(car_data)` observations (cars) of which most are priced between 10000 and 22500. While the histogram is skeewed to the right side there are only a significant amount of cars priced between 22500 and 45000. 

```{r}
#b)

car_small_cyl_vol <- car_data %>% filter(Liter < 3)
car_large_cyl_vol <- car_data %>% filter(Liter > 3)

  ### check whether below and above 3 liters includes all observations
  identical(nrow(car_small_cyl_vol)+nrow(car_large_cyl_vol),nrow(car_data))
  ##returns FALSE; hence it does not include all observations
  
  ### Cars with exactly 3 liters cylinder volume should be excluded after the constraints given in the exercise
  car_between_cyl_vol <- car_data %>% filter(Liter == 3)
  
  ### including 3 liter culinder volume cars as well yields the identical lenth of datasets
  identical(nrow(car_small_cyl_vol)+nrow(car_large_cyl_vol)+nrow(car_between_cyl_vol),nrow(car_data))

my_small <- car_small_cyl_vol$Liter
my_large <- car_large_cyl_vol$Liter

### Compute a t-test to test the null hypothesis for two means
t.test(my_small, my_large, conf.level = 0.99)


  ### We reject the null hypothesis that the population mean price of cars with a cylinder volume of more than 3 liters equals the population mean price of cars with a cylinder volume of more than 3 liters at a significance level of 0.01 as the constructed p-value is insignificant (i.e., very small)

#c)

price <- car_data$Price
liter <- car_data$Liter

### OLS estimation
lm_price_liter <- lm(price ~ liter)

summary(lm_price_liter)


### Computation of heteroscedasticity-robust standard errors
heterorob_SE <- sqrt(diag(vcovHC(lm_price_liter, type = "HC1")))
heterorob_SE

### Create table

### some explainng words here

#d)

### Plot and add prices vs. liter to regression line

plot(liter, price, pch = 16, cex = 1.3, col = "blue", main = "Price plotted against Liter", xlab = "Liter", ylab = "Price") + abline(lm_price_liter)

#e)

lm_price_origin_liter <- lm(price ~ 0 + liter)

heterorob_origin_SE <- sqrt(diag(vcovHC(lm_price_origin_liter, type = "HC1")))
heterorob_origin_SE

#f)
plot(liter, price, pch = 16, cex = 1.3, col = "blue", main = "Price plotted against Liter", xlab = "Liter", ylab = "Price", xlim=c(0,max(liter)), ylim = c(0, max(price))) + abline(lm_price_liter) + abline(lm_price_origin_liter, col = "grey")

#g)

summary(lm_price_origin_liter)

#h)

car_data_h <- select(car_data, Price, Liter, Mileage, Cruise, Sound, Leather)

lm_prices_all <- lm(data = car_data_h, Price ~ .)

#i)
summary(lm_prices_all)

#j)

car_data_j <- mutate(car_data_h, miles_30k = 1*(Mileage>30000))

lm_prices_all_30kmiles <- lm(data = car_data_j, Price ~ .)

summary(lm_prices_all_30kmiles)
```



